In [2]:
from pathlib import Path
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Load data

In [3]:
script = Path.cwd()
root = script.parent
df = pd.read_csv(root/"data"/"raw_data"/"data.csv")

In [4]:
df.head()

,Unnamed: 0,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,preferred_offer_types,...,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,0,18,F,XW0DQ7H,Village,Platinum Membership,17-08-2017,No,xxxxxxxx,Gift Vouchers/Coupons,...,300.63,53005.25,17,781.75,Yes,Yes,No,Not Applicable,Products always in Stock,0
1,1,32,F,5K0N3X1,City,Premium Membership,28-08-2017,?,CID21329,Gift Vouchers/Coupons,...,306.34,12838.38,10,NaN,Yes,No,Yes,Solved,Quality Customer Care,0
2,2,44,F,1F2TCL3,Town,No Membership,11-11-2016,Yes,CID12313,Gift Vouchers/Coupons,...,516.16,21027.00,22,500.69,No,Yes,Yes,Solved in Follow-up,Poor Website,1
3,3,37,M,VJGJ33N,City,No Membership,29-10-2016,Yes,CID3793,Gift Vouchers/Coupons,...,53.27,25239.56,6,567.66,No,Yes,Yes,Unsolved,Poor Website,1
4,4,31,F,SVZXCWB,City,No Membership,12-09-2017,No,xxxxxxxx,Credit/Debit Card Offers,...,113.13,24483.66,16,663.06,No,Yes,Yes,Solved,Poor Website,1

### **Column Description :** 
|**Columns**|**Detail**|
|-----------|----------| 
|**Age**    |The age of the customer|
|**gender** |Gender of the customer male/female|
|**security_no**|Ordered by security number|
|**region_category**|Type of region customer belongs to|
|**membership_category**|Type of membership the customer owns|
|**joining_date**|The date on which the customer started using the service of the company|
|**joined_through_referral**|Joined through referral codes|
|**referral_id**|Unique Referral Ids|
|**preferred_offer_types**|Offers preferred|
|**medium_of_operation**|The tool/device used for the process of using the service|
|**internet_option**|Type of internet used by the customer|
|**last_visit_time**|Last time the customer visited|
|**days_since_last_login**|No of times since the customer last logged in to|
|**avg_time_spent**|Average Time spent wiht the service procedure|
|**avg_transaction_value**|Average payment made|
|****||

In [5]:
print(f"Shape of the dataset:\nRows : {df.shape[0]}\nColumns : {df.shape[1]}",)

Shape of the dataset:
Rows : 36992
Columns : 24

## Column Info

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 36992 entries, 0 to 36991
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    36992 non-null  int64
 1   age                           36992 non-null  int64
 2   gender                        36992 non-null  str
 3   security_no                   36992 non-null  str
 4   region_category               31564 non-null  str
 5   membership_category           36992 non-null  str
 6   joining_date                  36992 non-null  str
 7   joined_through_referral       36992 non-null  str
 8   referral_id                   36992 non-null  str
 9   preferred_offer_types         36704 non-null  str
 10  medium_of_operation           36992 non-null  str
 11  internet_option               36992 non-null  str
 12  last_visit_time               36992 non-null  str
 13  days_since_last_login         36992 non-null  int64
 14  avg_time_spent                36992 non-null  float64
 15  avg_transaction_value         36992 non-null  float64
 16  avg_frequency_login_days      36992 non-null  str
 17  points_in_wallet              33549 non-null  float64
 18  used_special_discount         36992 non-null  str
 19  offer_application_preference  36992 non-null  str
 20  past_complaint                36992 non-null  str
 21  complaint_status              36992 non-null  str
 22  feedback                      36992 non-null  str
 23  churn_risk_score              36992 non-null  int64
dtypes: float64(3), int64(4), str(17)
memory usage: 11.5 MB

## Statistical Info

In [7]:
df.describe()

,Unnamed: 0,age,days_since_last_login,avg_time_spent,avg_transaction_value,points_in_wallet,churn_risk_score
count,36992.000000,36992.000000,36992.000000,36992.000000,36992.000000,33549.000000,36992.000000
mean,18495.500000,37.118161,-41.915576,243.472334,29271.194003,686.882199,0.540982
std,10678.814916,15.867412,228.819900,398.289149,19444.806226,194.063624,0.498324
min,0.000000,10.000000,-999.000000,-2814.109110,800.460000,-760.661236,0.000000
25%,9247.750000,23.000000,8.000000,60.102500,14177.540000,616.150000,0.000000
50%,18495.500000,37.000000,12.000000,161.765000,27554.485000,697.620000,1.000000
75%,27743.250000,51.000000,16.000000,356.515000,40855.110000,763.950000,1.000000
max,36991.000000,64.000000,26.000000,3235.578521,99914.050000,2069.069761,1.000000

**Changing data type for joining date from str to datetime**

In [8]:
df['joining_date'] = pd.to_datetime(df['joining_date'])

C:\Users\KIIT\AppData\Local\Temp\ipykernel_18808\313696224.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['joining_date'] = pd.to_datetime(df['joining_date'])

In [9]:
df["last_visit_time"] = pd.to_datetime(df["last_visit_time"], format="%H:%M:%S", errors="coerce")

Removing -ve day values
Fixing them with

In [10]:
df.loc[df['days_since_last_login']<0,'days_since_last_login'] = np.nan

In [11]:
df['days_since_last_login'].isna().sum()

np.int64(1999)

In [12]:
df['days_since_last_login'].fillna(0)

0        17.0
1        16.0
2        14.0
3        11.0
4        20.0
         ...
36987     2.0
36988    13.0
36989    12.0
36990    15.0
36991    15.0
Name: days_since_last_login, Length: 36992, dtype: float64

Converted the negatives as today logged in

In [13]:
df['avg_time_spent'].dtype

dtype('float64')

In [14]:
df.loc[df['avg_time_spent']<0] = np.nan

In [15]:
df['avg_time_spent'] = df['avg_time_spent'].fillna(0)

In [16]:
df['avg_time_spent'].isna().sum()

np.int64(0)

In [17]:
df.loc[df['referral_id']=="xxxxxxxx",'referral_id'] = "no referral id"

In [18]:
df.head()

,Unnamed: 0,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,preferred_offer_types,...,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,0.0,18.0,F,XW0DQ7H,Village,Platinum Membership,2017-08-17,No,no referral id,Gift Vouchers/Coupons,...,300.63,53005.25,17,781.75,Yes,Yes,No,Not Applicable,Products always in Stock,0.0
1,1.0,32.0,F,5K0N3X1,City,Premium Membership,2017-08-28,?,CID21329,Gift Vouchers/Coupons,...,306.34,12838.38,10,NaN,Yes,No,Yes,Solved,Quality Customer Care,0.0
2,2.0,44.0,F,1F2TCL3,Town,No Membership,2016-11-11,Yes,CID12313,Gift Vouchers/Coupons,...,516.16,21027.00,22,500.69,No,Yes,Yes,Solved in Follow-up,Poor Website,1.0
3,3.0,37.0,M,VJGJ33N,City,No Membership,2016-10-29,Yes,CID3793,Gift Vouchers/Coupons,...,53.27,25239.56,6,567.66,No,Yes,Yes,Unsolved,Poor Website,1.0
4,4.0,31.0,F,SVZXCWB,City,No Membership,2017-09-12,No,no referral id,Credit/Debit Card Offers,...,113.13,24483.66,16,663.06,No,Yes,Yes,Solved,Poor Website,1.0

In [19]:
df.loc[df['medium_of_operation']=='?','medium_of_operation'] = 'Not Provided'

In [20]:
df['medium_of_operation'].value_counts()

medium_of_operation
Desktop         13259
Smartphone      13208
Not Provided     5151
Both             3655
Name: count, dtype: int64

In [21]:
df['gender'].value_counts()

gender
F          17645
M          17573
Unknown       55
Name: count, dtype: int64

In [22]:
df['region_category'].value_counts()

region_category
Town       13489
City       12108
Village     4487
Name: count, dtype: int64

In [23]:
df['joined_through_referral'].value_counts()

joined_through_referral
No     15067
Yes    15033
?       5173
Name: count, dtype: int64

In [24]:
df.columns

Index(['Unnamed: 0', 'age', 'gender', 'security_no', 'region_category',
       'membership_category', 'joining_date', 'joined_through_referral',
       'referral_id', 'preferred_offer_types', 'medium_of_operation',
       'internet_option', 'last_visit_time', 'days_since_last_login',
       'avg_time_spent', 'avg_transaction_value', 'avg_frequency_login_days',
       'points_in_wallet', 'used_special_discount',
       'offer_application_preference', 'past_complaint', 'complaint_status',
       'feedback', 'churn_risk_score'],
      dtype='str')

In [25]:
df.columns

Index(['Unnamed: 0', 'age', 'gender', 'security_no', 'region_category',
       'membership_category', 'joining_date', 'joined_through_referral',
       'referral_id', 'preferred_offer_types', 'medium_of_operation',
       'internet_option', 'last_visit_time', 'days_since_last_login',
       'avg_time_spent', 'avg_transaction_value', 'avg_frequency_login_days',
       'points_in_wallet', 'used_special_discount',
       'offer_application_preference', 'past_complaint', 'complaint_status',
       'feedback', 'churn_risk_score'],
      dtype='str')

In [26]:
df.loc[df['joined_through_referral']=='?','joined_through_referral'] = 'No Information available'

In [27]:
names = {'age' : 'int64','gender' : str,'security_no' : str,'region_category' : str, 'membership_category' : str,
         'joining_date' : 'datetime','joined_through_referral' : str,'referral_id' : str,'preferred_offer_types' : str,'medium_of_operation' : str,
        'internet_option': str,'last_visit_time': str ,'days_since_last_login': 'int64','avg_time_spent': 'float64','avg_transaction_value':'float64'
         ,'avg_frequency_login_days': str,'points_in_wallet':'float64','used_special_discount':str,
         'offer_application_preference':str,'past_complaint':str,'complaint_status':str,'feedback' : str,'churn_risk_score':'float64'}

In [28]:
df['joined_through_referral'].value_counts()

joined_through_referral
No                          15067
Yes                         15033
No Information available     5173
Name: count, dtype: int64

In [29]:
def find_counts(df : pd.DataFrame):
    for col,data in names.items():
        if data == str :
            print('------------------------------------------')
            print(df[col].value_counts().reset_index(),'\n\n')
            print('------------------------------------------')
        else:
            print('------------------------------------------')
            print(df[col].value_counts().reset_index(),'\n\n')
            print('------------------------------------------')

In [30]:
find_counts(df)

------------------------------------------
     age  count
0   42.0    694
1   16.0    693
2   33.0    687
3   30.0    674
4   38.0    674
5   60.0    671
6   61.0    670
7   57.0    668
8   47.0    668
9   59.0    666
10  41.0    665
11  32.0    660
12  34.0    660
13  21.0    658
14  55.0    658
15  28.0    657
16  17.0    656
17  56.0    655
18  62.0    653
19  45.0    651
20  29.0    646
21  36.0    646
22  46.0    646
23  48.0    645
24  23.0    645
25  22.0    645
26  10.0    643
27  53.0    643
28  58.0    642
29  64.0    642
30  14.0    640
31  44.0    639
32  52.0    639
33  26.0    634
34  43.0    631
35  35.0    631
36  12.0    630
37  49.0    630
38  27.0    628
39  63.0    628
40  11.0    626
41  50.0    625
42  51.0    625
43  19.0    619
44  24.0    618
45  13.0    616
46  37.0    615
47  20.0    614
48  15.0    612
49  39.0    610
50  31.0    605
51  25.0    602
52  40.0    601
53  18.0    588
54  54.0    586


------------------------------------------
------------------------------------------
    gender  count
0        F  17645
1        M  17573
2  Unknown     55


------------------------------------------
------------------------------------------
      security_no  count
0         XW0DQ7H      1
1         5K0N3X1      1
2         1F2TCL3      1
3         VJGJ33N      1
4         SVZXCWB      1
...           ...    ...
35268     GWAHGJY      1
35269     8X0LUUS      1
35270     XK1IM9H      1
35271     K6VTP1Z      1
35272     LBX0GLR      1

[35273 rows x 2 columns]


------------------------------------------
------------------------------------------
  region_category  count
0            Town  13489
1            City  12108
2         Village   4487


------------------------------------------
------------------------------------------
   membership_category  count
0     Basic Membership   7346
1        No Membership   7320
2      Gold Membership   6494
3    Silver Membership   5729
4   Premium Membership   4246
5  Platinum Membership   4138


------------------------------------------
------------------------------------------
     joining_date  count
0      2015-06-02     53
1      2015-06-21     50
2      2015-07-04     48
3      2017-03-19     48
4      2015-01-05     47
...           ...    ...
1091   2016-03-16     18
1092   2017-07-03     18
1093   2015-11-12     17
1094   2015-09-12     17
1095   2015-03-04     15

[1096 rows x 2 columns]


------------------------------------------
------------------------------------------
    joined_through_referral  count
0                        No  15067
1                       Yes  15033
2  No Information available   5173


------------------------------------------
------------------------------------------
          referral_id  count
0      no referral id  16979
1            CID43705     11
2             CID3979     11
3            CID49601     10
4            CID49598      9
...               ...    ...
11048        CID56143      1
11049        CID48865      1
11050        CID60808      1
11051        CID10431      1
11052        CID45477      1

[11053 rows x 2 columns]


------------------------------------------
------------------------------------------
      preferred_offer_types  count
0     Gift Vouchers/Coupons  11761
1  Credit/Debit Card Offers  11717
2            Without Offers  11522


------------------------------------------
------------------------------------------
  medium_of_operation  count
0             Desktop  13259
1          Smartphone  13208
2        Not Provided   5151
3                Both   3655


------------------------------------------
------------------------------------------
  internet_option  count
0           Wi-Fi  11845
1     Mobile_Data  11722
2     Fiber_Optic  11706


------------------------------------------
------------------------------------------
          last_visit_time  count
0     1900-01-01 07:56:41      6
1     1900-01-01 21:12:56      5
2     1900-01-01 12:30:02      5
3     1900-01-01 11:40:04      4
4     1900-01-01 15:39:51      4
...                   ...    ...
28960 1900-01-01 10:53:31      1
28961 1900-01-01 15:41:36      1
28962 1900-01-01 05:29:19      1
28963 1900-01-01 09:50:03      1
28964 1900-01-01 01:39:52      1

[28965 rows x 2 columns]


------------------------------------------
------------------------------------------
    days_since_last_login  count
0                    12.0   2275
1                    13.0   2244
2                    14.0   2211
3                    15.0   2161
4                    11.0   2149
5                    10.0   2010
6                    16.0   1970
7                     9.0   1768
8                    17.0   1666
9                     8.0   1495
10                   18.0   1393
11                    7.0   1375
12                   19.0   1254
13                    6.0   1199
14                    5.0   1168
15                   20.0   1141
16                   21.0    976
17                    4.0    953
18                   22.0    856
19                    3.0    802
20                   23.0    692
21                    2.0    580
22                   24.0    442
23                    1.0    316
24                   25.0    187
25                   26.0     75


------------------------------------------
------------------------------------------
       avg_time_spent  count
0                0.00   1719
1               34.10     21
2               34.71     20
3               33.68     20
4               34.33     19
...               ...    ...
24237          122.44      1
24238           49.33      1
24239          418.38      1
24240          154.94      1
24241          482.61      1

[24242 rows x 2 columns]


------------------------------------------
------------------------------------------
       avg_transaction_value  count
0                   23397.98      2
1                    7282.58      2
2                   30761.37      2
3                   13788.92      2
4                   35460.38      2
...                      ...    ...
35175               56397.21      1
35176                8225.68      1
35177               38127.56      1
35178                2378.86      1
35179                2189.68      1

[35180 rows x 2 columns]


------------------------------------------
------------------------------------------
     avg_frequency_login_days  count
0                       Error   3342
1                          13   1331
2                          14   1298
3                           8   1296
4                          17   1289
...                       ...    ...
1561              44.72308933      1
1562              52.93447403      1
1563             -9.325511142      1
1564             -8.759329713      1
1565              27.83992744      1

[1566 rows x 2 columns]


------------------------------------------
------------------------------------------
       points_in_wallet  count
0            705.070000      9
1            780.920000      8
2            760.540000      7
3            710.690000      7
4            760.760000      6
...                 ...    ...
22881        699.400000      1
22882       1251.708596      1
22883       1096.932079      1
22884        242.979625      1
22885        197.264414      1

[22886 rows x 2 columns]


------------------------------------------
------------------------------------------
  used_special_discount  count
0                   Yes  19407
1                    No  15866


------------------------------------------
------------------------------------------
  offer_application_preference  count
0                          Yes  19513
1                           No  15760


------------------------------------------
------------------------------------------
  past_complaint  count
0             No  17745
1            Yes  17528


------------------------------------------
------------------------------------------
           complaint_status  count
0            Not Applicable  17745
1                  Unsolved   4419
2                    Solved   4411
3       Solved in Follow-up   4353
4  No Information Available   4345


------------------------------------------
------------------------------------------
                   feedback  count
0      Poor Product Quality   6045
1       No reason specified   6000
2              Poor Website   5979
3              Too many ads   5979
4     Poor Customer Service   5973
5          Reasonable Price   1345
6     User Friendly Website   1336
7  Products always in Stock   1323
8     Quality Customer Care   1293


------------------------------------------
------------------------------------------
   churn_risk_score  count
0               1.0  19049
1               0.0  16224


------------------------------------------

In [31]:
df.head()

,Unnamed: 0,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,preferred_offer_types,...,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,0.0,18.0,F,XW0DQ7H,Village,Platinum Membership,2017-08-17,No,no referral id,Gift Vouchers/Coupons,...,300.63,53005.25,17,781.75,Yes,Yes,No,Not Applicable,Products always in Stock,0.0
1,1.0,32.0,F,5K0N3X1,City,Premium Membership,2017-08-28,No Information available,CID21329,Gift Vouchers/Coupons,...,306.34,12838.38,10,NaN,Yes,No,Yes,Solved,Quality Customer Care,0.0
2,2.0,44.0,F,1F2TCL3,Town,No Membership,2016-11-11,Yes,CID12313,Gift Vouchers/Coupons,...,516.16,21027.00,22,500.69,No,Yes,Yes,Solved in Follow-up,Poor Website,1.0
3,3.0,37.0,M,VJGJ33N,City,No Membership,2016-10-29,Yes,CID3793,Gift Vouchers/Coupons,...,53.27,25239.56,6,567.66,No,Yes,Yes,Unsolved,Poor Website,1.0
4,4.0,31.0,F,SVZXCWB,City,No Membership,2017-09-12,No,no referral id,Credit/Debit Card Offers,...,113.13,24483.66,16,663.06,No,Yes,Yes,Solved,Poor Website,1.0

In [32]:
df.shape[0]

36992

In [33]:
df.isna().sum()

Unnamed: 0                      1719
age                             1719
gender                          1719
security_no                     1719
region_category                 6908
membership_category             1719
joining_date                    1719
joined_through_referral         1719
referral_id                     1719
preferred_offer_types           1992
medium_of_operation             1719
internet_option                 1719
last_visit_time                 1719
days_since_last_login           3634
avg_time_spent                     0
avg_transaction_value           1719
avg_frequency_login_days        1719
points_in_wallet                5011
used_special_discount           1719
offer_application_preference    1719
past_complaint                  1719
complaint_status                1719
feedback                        1719
churn_risk_score                1719
dtype: int64

In [34]:
df['age'].isna().sum()

np.int64(1719)

In [35]:
len(df.columns)

24

In [36]:
def smart_fillna(df: pd.DataFrame):
    for col,data in names.items():
        if data == str:
            print('-----------------------------------------')
            df[col] = df[col].fillna('No data available')
            print(f'Filled {col} with No data available')
        else:
            print('-----------------------------------------')
            fill = df[col].median()
            df[col] = df[col].fillna(fill)
            print(f'Filled {col} with {fill}')

In [37]:
smart_fillna(df)

-----------------------------------------
Filled age with 37.0
-----------------------------------------
Filled gender with No data available
-----------------------------------------
Filled security_no with No data available
-----------------------------------------
Filled region_category with No data available
-----------------------------------------
Filled membership_category with No data available
-----------------------------------------
Filled joining_date with 2016-07-06 00:00:00
-----------------------------------------
Filled joined_through_referral with No data available
-----------------------------------------
Filled referral_id with No data available
-----------------------------------------
Filled preferred_offer_types with No data available
-----------------------------------------
Filled medium_of_operation with No data available
-----------------------------------------
Filled internet_option with No data available
-----------------------------------------
Filled last_visit_time with No data available
-----------------------------------------
Filled days_since_last_login with 13.0
-----------------------------------------
Filled avg_time_spent with 161.765
-----------------------------------------
Filled avg_transaction_value with 27543.12
-----------------------------------------
Filled avg_frequency_login_days with No data available
-----------------------------------------
Filled points_in_wallet with 698.03
-----------------------------------------
Filled used_special_discount with No data available
-----------------------------------------
Filled offer_application_preference with No data available
-----------------------------------------
Filled past_complaint with No data available
-----------------------------------------
Filled complaint_status with No data available
-----------------------------------------
Filled feedback with No data available
-----------------------------------------
Filled churn_risk_score with 1.0

In [38]:
df.isna().sum()

Unnamed: 0                      1719
age                                0
gender                             0
security_no                        0
region_category                    0
membership_category                0
joining_date                       0
joined_through_referral            0
referral_id                        0
preferred_offer_types              0
medium_of_operation                0
internet_option                    0
last_visit_time                    0
days_since_last_login              0
avg_time_spent                     0
avg_transaction_value              0
avg_frequency_login_days           0
points_in_wallet                   0
used_special_discount              0
offer_application_preference       0
past_complaint                     0
complaint_status                   0
feedback                           0
churn_risk_score                   0
dtype: int64

In [39]:
df.to_csv(root/"data"/"cleaned_data"/"cleaned_data.csv",index= False)
print(f"Successfully saved cleaned data to {root/"data"/"cleaned_data"/"cleaned_data.csv"} ✅")

Successfully saved cleaned data to d:\Customer Segmntation and retention analysis\data\cleaned_data\cleaned_data.csv ✅